server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/category_service_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # use "create" for first time if you want fresh table
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  application:
    name: category-service
